name: salesforce_spo
description: A flutter project for The Guitar Center sales agents across various stores.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_svg: ^1.0.3
  http:
  shared_preferences:
  url_launcher: ^6.1.0
#  azure_ad_authentication: ^1.0.3
  intl: ^0.17.0
  fl_chart: ^0.50.6
  expandable: ^5.0.1
  easy_debounce: ^2.0.2+1
  flutter_slidable:
  dotted_border: ^2.0.0+2
  cached_network_image: ^3.2.1
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/music_icons/
    - assets/icons/landing_icons/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik_regular.ttf
        - asset: assets/fonts/rubik_semiBold.ttf
          weight: 600

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
